archlinux-seckernel: customize kernel build and add 2 patches
Signed-off-by: Nicolas Iooss <nicolas.iooss_git@polytechnique.org>

diff --git a/archlinux-seckernel/arch-linux-grsec b/archlinux-seckernel/arch-linux-grsec
--- a/archlinux-seckernel/arch-linux-grsec
+++ b/archlinux-seckernel/arch-linux-grsec
@@ -1,34 +1,14 @@
 #!/bin/sh
 # Build linux-grsec package for ArchLinux
-#
-# Patch the AUR package to disable sysfs protection because many Desktop
-# application needs it (network interface enumeration, audio card settings, ...)
-#
-# PolicyKit needs full access to /proc to be able to find process owner from a
-# PID. To do that, users dbus and polkitd should belong to group "proc-trusted"
-# (maybe only one of these users... This needs more testing).
-# This configuration is achieved by following commands:
-#     gpasswd proc-trusted -a dbus
-#     gpasswd proc-trusted -a polkitd
-#
-# NTPd needs to read /proc/net/if_inet6 to work in IPv6
-# (see http://support.ntp.org/bin/view/Support/KnownOsIssues#Section_9.2.4.2.5.1.)
-#     gpasswd proc-trusted -a ntp
-#
-# To grant an user the right to execute its own executables, he must belong to
-# group "tpe-trusted". Also, to do administrative actions without being root,
-# being member of group "adm" is a good idea.
-#
-# Use linux-pax-flags (from linux-pax-flags package) to apply PAX configuration
-# to the most common applications of your system, then use paxctl with other
-# binaries if needed. For example:
-#     paxctl -cPSmXER /usr/bin/truecrypt
-# You may edit files in /etc/pax-flags/ to modify linux-pax-flags targets.
 
 # Download Archive from AUR and extract it in a temporary folder
-ARCHIVE=linux-grsec.tar.gz
+ARCHIVE='linux-grsec.tar.gz'
 AUR_URL='https://aur.archlinux.org/packages/li/linux-grsec/linux-grsec.tar.gz'
-TEMP_DIR=/tmp/linux-grsec-build
+TEMP_DIR="${TEMP_DIR:-/tmp/linux-grsec-build}"
+
+# Save current path
+cd $(dirname $0)
+SCRIPT_DIRECTORY="$(pwd -P)"
 
 # Work in temporary directory
 [ -d "$TEMP_DIR" ] || mkdir -p "$TEMP_DIR"
@@ -41,9 +21,18 @@ fi
 # If ARCHIVE is recent enougth, don't download it again
 if ! (find "$ARCHIVE" -type f -mtime -1 2> /dev/null |grep -q "$ARCHIVE")
 then
-    echo "Download $ARCHIVE"
-    ! [ -e "$ARCHIVE" ] || mv "$ARCHIVE" "OLD-$ARCHIVE"
-    ! [ -e linux-grsec ] || mv linux-grsec OLD-linux-grsec
+    echo >&2 "Download $ARCHIVE"
+    rm -f "$ARCHIVE"
+    if [ -e linux-grsec ]
+    then
+        if [ -e OLD-linux-grsec ]
+        then
+            echo >&2 "$TEMP_DIR/OLD-linux-grsec already exist"
+            echo >&2 "failed to backup existing linux-grsec directory"
+            exit 1
+        fi
+        mv linux-grsec OLD-linux-grsec
+    fi
     wget -O "$ARCHIVE" "$AUR_URL"
     touch "$ARCHIVE"
 fi
@@ -64,26 +53,14 @@ then
     exit 1
 fi
 
-# Patch default config:
-#   Location:
-#     -> Security options
-#       -> Grsecurity
-#         -> Grsecurity (GRKERNSEC [=y])
-#           -> Customize Configuration
-#             -> Filesystem Protections
-#               [ ] Sysfs/debugfs restriction
-#-CONFIG_GRKERNSEC_SYSFS_RESTRICT=y
-#+# CONFIG_GRKERNSEC_SYSFS_RESTRICT is not set
-# and set CONFIG_DEFAULT_MMAP_MIN_ADDR=65536
-# Note: this should become 32768 on arm architectures
+# Update kernel configuration
+# Please read README.rst file for more information.
 for CONFIG_FILE in config.i686 config.x86_64
 do
-    OLD_SIG=$(sha256sum $CONFIG_FILE |cut -d\  -f1)
-    sed 's/CONFIG_GRKERNSEC_SYSFS_RESTRICT=y/# CONFIG_GRKERNSEC_SYSFS_RESTRICT is not set/' -i $CONFIG_FILE
-    sed 's/^.*CONFIG_DEFAULT_MMAP_MIN_ADDR=.*/CONFIG_DEFAULT_MMAP_MIN_ADDR=65536/' -i $CONFIG_FILE
-    # Add SELinux support, if not already enabled
-    # Note: by default, SELinux is not enabled at all on ArchLinux
-    if ! grep -q 'CONFIG_SECURITY_SELINUX=y' < $CONFIG_FILE
+    OLD_SIG=$(sha256sum "$CONFIG_FILE" |cut -d\  -f1)
+    sed 's/CONFIG_GRKERNSEC_SYSFS_RESTRICT=.*/# CONFIG_GRKERNSEC_SYSFS_RESTRICT is not set/' -i "$CONFIG_FILE"
+    sed 's/^.*CONFIG_DEFAULT_MMAP_MIN_ADDR=.*/CONFIG_DEFAULT_MMAP_MIN_ADDR=65536/' -i "$CONFIG_FILE"
+    if ! grep -q 'CONFIG_SECURITY_SELINUX=y' < "$CONFIG_FILE"
     then
         cat >> $CONFIG_FILE << EOF
 CONFIG_SECURITY_SELINUX=y
@@ -99,13 +76,33 @@ CONFIG_LSM_MMAP_MIN_ADDR=65536
 CONFIG_DEFAULT_SECURITY_SELINUX=y
 EOF
     fi
-    NEW_SIG=$(sha256sum $CONFIG_FILE |cut -d\  -f1)
+    NEW_SIG=$(sha256sum "$CONFIG_FILE" |cut -d\  -f1)
     if [ "$OLD_SIG" != "$NEW_SIG" ]
     then
-        echo >&2 "File $CONFIG_FILE was updated"
+        echo >&2 "File $CONFIG_FILE has been updated, update PKGBUILD"
         sed "s/$OLD_SIG/$NEW_SIG/" -i PKGBUILD
     fi
 done
+
+# Add custom patches
+for PATCH in bugon-add-null-timer.patch usr-bin-usermode-helper.patch
+do
+    if [ ! -e "$PATCH" ] && ! cp "$SCRIPT_DIRECTORY/$PATCH" "$PATCH"
+    then
+        echo >&2 "Failed to copy $PATCH"
+        exit 1
+    fi
+done
+
+# Don't apply PKGBUILD.patch twice
+if ! grep -q 'bugon-add-null-timer.patch' PKGBUILD
+then
+    if ! patch -p1 < "$SCRIPT_DIRECTORY/PKGBUILD.patch"
+    then
+        echo >&2 "Failed to patch PKGBUILD"
+        exit 1
+    fi
+fi
 
 # Configure make variables
 MENUCONFIG=${MENUCONFIG:-0}
