archlinux-seckernel/download_grsec: create symlinks to latest patch and the one before
This eases diffing analysis

diff --git a/archlinux-seckernel/download_grsec b/archlinux-seckernel/download_grsec
--- a/archlinux-seckernel/download_grsec
+++ b/archlinux-seckernel/download_grsec
@@ -25,21 +25,29 @@ PATCH_PATH="$PATCH_DIR/$PATCH_FILE"
 if [ -e "$PATCH_PATH" ]
 then
     echo "Last patch already downloaded in $PATCH_PATH"
-    exit
+else
+    echo "Downloading $PATCH_URL..."
+    [ -e "$PATCH_PATH" ] || curl -o "$PATCH_PATH" "$PATCH_URL" || exit $?
+
+    # Verify the GPG signature
+    echo "Downloading $PATCH_URL.sig..."
+    curl -o "$PATCH_PATH.sig" "$PATCH_URL.sig" || exit $?
+
+    if ! gpg --verify "$PATCH_PATH.sig"
+    then
+        echo >&2 "GPG verification failed. Renaming patch $PATCH_PATH.bad"
+        mv -v "$PATCH_PATH" "$PATCH_PATH.bad"
+        exit 1
+    fi
+
+    echo "grsec patch downloaded in $PATCH_PATH"
 fi
 
-echo "Downloading $PATCH_URL..."
-[ -e "$PATCH_PATH" ] || curl -o "$PATCH_PATH" "$PATCH_URL" || exit $?
-
-# Verify the GPG signature
-echo "Downloading $PATCH_URL.sig..."
-curl -o "$PATCH_PATH.sig" "$PATCH_URL.sig" || exit $?
-
-if ! gpg --verify "$PATCH_PATH.sig"
+# Create symlinks to the latest and the one before
+ln -fsv "$PATCH_FILE" "$PATCH_DIR/latest.patch"
+PREV_LATEST="$(find "$PATCH_DIR" -name 'grsecurity-*.patch' -not -name "$PATCH_FILE" -printf '%f\n' |\
+    LANG=C sort -nr | head -n 1)"
+if [ -n "$PREV_LATEST" ]
 then
-    echo >&2 "GPG verification failed. Renaming patch $PATCH_PATH.bad"
-    mv -v "$PATCH_PATH" "$PATCH_PATH.bad"
-    exit 1
+    ln -fsv "$PREV_LATEST" "$PATCH_DIR/before-latest.patch"
 fi
-
-echo "grsec patch downloaded in $PATCH_PATH"
